### ISSUE TITLE
[charter] Focus on environmental issues, over social or governmental ones

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#103]
I recognize that sustainability is broader than just environmental issues, but in order to maximize the chance that the proposed WG can get W3C consensus around an actionable specification, I suggest that the first charter for the WG focus on just the most concrete and measurable environmental issues. Once the WG has a successful track record in this part of the space, it'll make sense to broaden the charter to address more aspects of sustainability.

**Comment by AlexDawsonUK** [comment]
We've spoken about this issue at meetings and we have not reached a consensus about going down this path.

Assuming we go down the IG route we should potentially have more flexibility in scope as we would first propose a note, that along with the fact that we will be working hard to improve measurability (we have been listening to everyones feedback) may be enough to address this concern - though I'm open to this solution as a way to reduce friction if we can't meet such a threshhold getting to publication.

I'll leave this issue open as I'm curious as to others viewpoints!

**Comment by AlexDawsonUK** [comment]
At our last meeting the idea of separating environment from other concerns was met with a lot of concern due to the inherent tie-in with sustainability and wider aspects being within scope not only in a legal compliance perspective but also for the benefits it brings to people and the planet.

Because of this, as denoted above we shall initially attempt to maintain a wide scope (with better measurability and tie-in with technology and the Internet as we evolve the specification) and hope this is enough to produce an IG worthy note to statement. If issues do occur, this path can be re-examined in the future by the group.

I'll close this issue as resolved for the moment and it can be reignited as required in the future.
