### ISSUE TITLE
Future Scope

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#13]
Discuss the future reach of the guidelines:
- Just Websites
- Applications
- Browsers / Tooling
- Other Specifications (Interconnecting)
- Hardware (?)

How will the specification grow to account for this (future notes, further specifications, horizontal review, etc).
Collaboration (WAI / Equity CG / Sustainability CG / W3C PING / Privacy CG / WebPerf WG / etc)

**Note:** To be discussed at a later CG meeting, comments welcome below with future ideas.
**Credit:** npd, @jenstrickland, @npdoty, @notmariazoe

**Comment by OR13** [comment]
it seems like you can divide W3C specs into several categories, each have their own sustainability challenges.

1. Standards for Native APIs (for example web crypto / webauthn / credential manager / web bluetooth / web nfc / mdoc request api, etc)
2. Standards for languages (for example CSS / JSON-LD / XML / HTML)
3. Standards for profiles on languages (Verifiable Credentials builds on JSON-LD, mDoc Request API builds on ISO mDoc)

You can have problematic resource consumption at each of these layers, but the most critical and the native APIs, since they tend to be close to the hardware (consider webgpu crypto currency miners, or advanced video processing capabilities).

**Comment by AlexDawsonUK** [comment]
I've marked this on the agenda for one of our meetings this month (October 23). This issue can be re-opened at a later date if our scope needs to be altered or if our groups status requires the issue being re-examined.
