### ISSUE TITLE
Contributor suggestion: allow/promote pull requests

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#16]
I would really like to make a pull request to these guidelines (once Ive read them closely!) and I would like to explain and justify why that should be an option.

The ability to make a pull request (and possibly have it accepted) gives a certain amount of recognition for potential open source contributors, who get the joy and recognition of basically having made a concrete contribution to the texts. I think it serves the same function or purpose as having "easy" `first issue` issues to get more contributors onboard - the contributors get to say they contributed to a guideline!

Instead of having just an option to file an issue, maybe instructions should be given how to edit the guidelines.

Thank you for considering my suggestion at all,

Morgan @airbr

**Comment by airbr** [comment]
On second thought, a lot of process heavy stuff probably went into each guideline over months and years, but that doesnt preclude having an open facing angle for a motivated contributor

**Comment by AlexDawsonUK** [comment]
@airbr Thanks for your suggestion. This is something we will be talking about at our next meeting.

As you mentioned, our work has gone through a lot of review processes to ensure high content-quality and to maintain the best evidence base possible so we would need to be considerate of this when deciding upon whether to accept pull requests (we are at a very early stage after all).

I do absolutely agree that open source contributors should be given recognition for their work. This is something we maintained through the initial publication process (see Acknowledgements in the spec), and we will continue to do. More clarification could definitely be useful in the README so I'll add that to the list, but regarding the issue system, there's nothing to stop an individual who submits some great material via this (such as yourself) from being credited as and when it makes it into the specification.

**Example:** You submit a potential guideline as an issue, it goes through our review process, it gets approved, it makes the next draft and you'll be credited both within the GitHub Releases (version log) and notably within the Spec Acknowledgments.

Of course, there's nothing to stop us using pull requests as well, but our group will need to discuss the logistics of it.

**Comment by AlexDawsonUK** [comment]
After discussion and consideration, at this point in time we won't be utilizing pull requests for the following reasons:
- Because our work has to go through several review processes, having pull requests (which apply live to the work) would pose quality control issues against the measures we currently have in place.
- The W3C system we use to produce and format the specification (ReSpec) has dependencies, and this month we experienced an outage which would have left the content in a partially unformatted / unavailable state if it weren't for the precautions taken to export the finished draft into a pure W3C formatted HTML document (which has no dependancies). As you can imagine, for something as critical as our work, we wish to reduce tooling reliance wherever possible.

**Note:** With this being said, we will be formalizing a system so that all willing contributors can get involved and directions are made clear for where efforts would be handy (so people can jump in easily without barriers to entry).

This will be published as work on the second draft fully gets underway.
