### ISSUE TITLE
First reaction: Edge Computing Guideline

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#17]
I just wanted to share an experience I had reading the WSG 1.0 with another friend, specifically about one guideline that was interesting to me:

https://w3c.github.io/sustyweb/#use-edge-computing

My instinctual reaction was that using CDNs used more resources for more performance. Running many machines with many copies of the data but apparently cutting the network distance down helps cut emissions in a more significant way and the guideline made points I had never considered like reducing drain on a devices battery power. 

My speculation is this: `there must be some minimum traffic amount that makes it worthwhile`.

Still, it feels a little different and unusual, to recommend to use Edge Computing overall compared to other guidelines. I just make an observation that I am a pretty regular web dev and I deploy some things with a service called Netlify, which bills itself as an Edge provider, but I basically don't know that impact is. It is just a question I have, I will learn more about. 

Im just trying to imagine some kind of onboarding path to learn about Edge Computing for a 'regular dev' and not just high level infra provider using these standards. Some charts or graphics or more resources to explore "is Edge necessary or right for me" would be a possible goal.

**Comment by airbr** [comment]
I returned to look at the Details/Summary section of the resources and this could possibly answer my questions but there is a lot of stuff I still need to learn.

I revise my comment into a headline suggestion:

`Use Edge Computing` could become `Consider Edge Computing`

**Comment by AlexDawsonUK** [comment]
One point to make is that the server will only become active for that data request when it is required, in-effect - if your website does not have many visitors, your edge impact will likely be minimal. It also should be considered that having machines closer to your physical location uses fewer resources due to the energy emitted in transmitting data through networking equipment around the world (and through multiple servers itself) to reach the users device.

There is of course the point you make that having multiple copies of your data has an initial impact (not only in the creation and transfer of that website, but in the storage - even if it isn't used as infrastructure will need to upgrade (using minerals and producing eWaste) in order to meet demands. But the current weight of evidence leans towards static content being a net benefit if utilizing edge resources (due to mass visitor requests being more detrimental than the initial site distribution).

I do agree though there will always be edge cases, especially with something with as many variables involved as data transfer so using softer wording may be more appropriate. It'll be considered for the next draft.

**Comment by AlexDawsonUK** [comment]
The upcoming draft now states "Consider CDN's And Edge Caching" to better reflect the content and to soften the wording as stated by yourself within this issue and expanded upon within https://github.com/w3c/sustyweb/issues/24.
