### ISSUE TITLE
Headline wrapping on smaller mobile viewports

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#18]
Maybe not an issue, but could appear incorrect to some mobile users.

For example, an iPhone SE at 375 width:

![w3c github io_sustyweb_(iPhone SE)](https://github.com/w3c/sustyweb/assets/18056682/8a1f18ed-4fbb-4fc5-83e8-a8ccf3b7e1cc)

**Comment by AlexDawsonUK** [comment]
This isn't something we have control over, as the specification default styles are standardized (once compiled) by [ReSpec](https://respec.org/docs/).
Please file an issue with the appropriate [GitHub repo](https://github.com/w3c/respec/issues) to see if they can offer a resolution.

**Comment by AlexDawsonUK** [comment]
**Update:** ReSpec does have some allowances for custom coding (though it's very rigid and I can't guarantee it'll work) so I'll try some custom styles in the next draft. It's still worth flagging up an issue for scalable typography for different resolutions with their team though.

**Comment by AlexDawsonUK** [comment]
I have checked this, and due to the title being automatically generated by ReSpec, it's beyond the scope of this group to be able to resolve the visual inconsistency. I suggest an issue is raised with their team (as denoted above) to fix the formatting quirk which may occur for some readers. As such, I will mark this issue as unresolvable.
