### ISSUE TITLE
Permanent URI – Cool URIs don't change

### ISSUE THREAD

**Issue by signalwerk** [w3c/sustyweb#32]
According to Tim Berners-Lee [«Cool URIs don't change»](https://www.w3.org/Provider/Style/URI);

I just came across this awesome «Web Sustainability Guidelines (WSG) 1.0». Great document! I would like to do some communication about it, and I know the URL will then be baked into several other documents. The URI `https://w3c.github.io/sustyweb/` won't be the final destination for this document, I suppose. Can you offer me a permanent URI?

**Comment by AlexDawsonUK** [comment]
Hello @signalwerk.
Allow me to provide some insight into our structure and perhaps this will help clarify things.
At this stage we are a W3C Community Group. Because our work is a draft (and we're actively working on it, and providing improvements as we speak, as the second draft is underway), our work isn't in a finalized state so we cannot present a final report to the W3C and state that our work has concluded. Due to this our work currently resides here on our GitHub pages repo at the URI you've mentioned as a living document (which will be updated as necessary).

To offer a "permanent" URI one of two things would have to occur:
- Either we wind up our activity and present our work to the W3C as a final report saying "we're done", at which point it would be hosted within their materials.
- We form a working group around our work (which takes time), become W3C members & invited experts to manage the project from within the W3C, and therefore the project will have a permanent URI home from within the W3C itself.

In the long-run we prefer the latter as the track to standardization is something which has come up multiple times at meetings, and as our work is so closely aligned in content terms to specs like WCAG, it makes sense (especially as the W3C are now very much sustainability minded). However, this ultimately will take time (and we're under no illusions about this) so for the time being, we're keeping our work open, living and in-state here.

What I can say is if things should change and our structure does alter, we shall do our best to redirect traffic to any new location as appropriate. As our work evolves to meet any W3C (or additional regulatory) requirements.

I hope this is useful, if you have further questions, feel free to respond below!

**Comment by signalwerk** [comment]
@AlexDawsonUK thank you for your extensive and thoughtful answer. Because it's so early, I might wait with my communication then to get a bit more «stability» to the project and the URI. Thank you.
