### ISSUE TITLE
3.14 (proposal) : mobile-first should only be applied if relevant

### ISSUE THREAD

**Issue by JulienWilhelm** [w3c/sustyweb#34]
The guideline defines the “mobile-first” approach as still relevant. But there may be cases where this is not the case (for example, when creating a desktop-only experience).

This should be specified.

**Comment by AlexDawsonUK** [comment]
I have serious concerns about making this change. Should we be advocating for exclusionary edge-cases?

Many individuals (worldwide) will be browsing the web on their only device (a handheld one) and advocating from a sustainability specification that it's fine to produce a desktop only website will encourage website makers to introduce barriers to entry which will exclude an ever-increasing group of people (often at the lower end of the income scale, including those from developing nations). It will also potentially increase the risk of e-Waste by encouraging people to purchase equipment they might not otherwise have needed just because of unnecessary product requirements.

Web technologies as they currently stand have little difference in terms of rendering capabilities from Desktop to Mobile (excluding a few Safari quirks) and therefore I can see no justification why a desktop only site would be necessary when both types of device are equally capable of viewing the same content (if adapted correctly).

Do you have an example of a desktop-only experience which mobile cannot replicate? If you did then it could serve as a justification potentially, but as it stands I don't want people using our groups work to start reducing compatibility!

**Comment by JulienWilhelm** [comment]
I understand your doubts, Alex!

I agree that all terminals (mobile or desktop) have the same or almost the same web APIs. It's more about the user's ability to interact with a user interface that is too dense to fit on mobile, or whose interaction areas are too small. What if interacting with hover was a necessity? Can we even imagine every web app being mobile-friendly? If I run Adobe XD or Teams as a WebApp on desktop, can we imagine it will be the same version on mobile? I suppose not, there is a dedicated version (sometimes a mobile native version), with specific features for both versions. There are also professional (internal) applications that run only on desktop (for good or bad reasons).
 
I don't necessarily have very specific examples, but I think it's a good point to keep the discussion open to other points of view.

**Comment by AlexDawsonUK** [comment]
Interacting with hover is now possible thanks to CSS3 Pointer media queries (it's supported across the board and has been for some time now). Additionally, progressive disclosure answers the question about information dense pages, either using the target pseudo, the dialog element, the details element or using responsive design to layout your information in a different manner on mobile to desktop, there is no reason why a web app cannot offer the same as a desktop version, just the layout will naturally differ because of the visitor will use it in a slightly different way.

**PS:** It's technically possible to run Visual Studio Code on an iPhone (not that you'd ideally want too). And if you can run a full-suite development IDE on a small screen and not encounter any UX issues (aside from having to type on a virtual keyboard), what excuse really is there for anyone else to avoid compatibility.

**Comment by AlexDawsonUK** [comment]
I will mark this issue as not planned at the moment, but it can be discussed further to decide if additional clarification is necessary and if so, which guideline or success criteria it should best fall under (so feel free to keep posting comments!).
