### ISSUE TITLE
New content about the `Use Beneficial JavaScript and Its API's` [3.15]

### ISSUE THREAD

**Issue by DocRoms** [w3c/sustyweb#48]
**Issue :** 
The section [3.15] `Use Beneficial JavaScript and Its API's` has actually two criteria:

 - Improve sustainability through accessible and performant code implementations.
 - When using an API, make sure you only call it when necessary. On the other side, make sure no
unrequired data is sent by the API.

It is actually more efficient to use native JavaScript APIs, which are efficient, than to load additional code that will do the same thing.

However, I think it may be useful to add a point about taking code backwards into account when using them.

If we add a recent API that is only supported on x% of browsers, it would force users to change browsers, or even devices if they cannot receive an update. And this is exactly what we want to avoid in terms of ecodesign. 

**Solution :** 
To add a criterion to propose to check API backwards compatibility (ex : https://caniuse.com/view-transitions), or use a polyfill (like https://www.npmjs.com/package/fetch-polyfill)  : 
- When using an API, make sure this one that it has the greatest possible compatibility, or use a polifill if the code may not work on many browsers.

I don't now if this point is "included" by the first one : " Improve sustainability through accessible and performant code implementations". What do you think ?

**Note**
 - If you have any further comments, don't hesistate to add it below !
 - Sorry about my english :)

**Comment by AlexDawsonUK** [comment]
We already have a quite extensive guideline ([2.29](https://w3c.github.io/sustyweb/#incorporate-compatibility-testing-into-each-release-cycle)) regarding compatibility (remember, while it may be in the UX section, there is a lot of cross-over with multiple guidelines so what applies to one section will also apply to another).

It does speak about old browsers and software versions which by design would naturally be the cause of API or code compatibility (as the browser engine determines what version of ECMAScript, API's, bits of HTML, CSS, etc it can work with).

I'll mark this as not planned (but open for further discussion) at this point as we already have something similar in place - though if you think the wording needs to be more explicit, feel free to add a reply because I'd be happy to add a Success Criteria (or improve the existing one) regarding code if it feels like something is missing.
