### ISSUE TITLE
Define the 6 core principle

### ISSUE THREAD

**Issue by gagarine** [w3c/sustyweb#5]
The core principles outlined on https://www.sustainablewebmanifesto.com/ appear somewhat ambiguous to me. They originated from https://www.wholegraindigital.com and seem insufficiently robust to serve as the basis for a W3C Guideline, though I could be mistaken.

**For reference those are the 6 principles:**

> 1. Clean: We commit to providing and utilizing services powered by renewable energy.
> 2. Efficient: Our products and services will strive for the minimal usage of energy and material resources.
> 3. Open: We promise accessibility, the free exchange of information, and enabling users to control their data in all our products and services.
> 4. Honest: We pledge not to use deceptive or exploitative designs or content in our products and services.
> 5. Regenerative: We aim to support an economy conducive to both human well-being and environmental sustainability through our products and services.
> 6. Resilient: Our products and services will be reliable, functioning when and where people need them most.

For instance, why is the 'clean' principle exclusively defined by renewable energy, neglecting other resources? How is 'efficiency', as a principle, distinct enough from 'clean' to warrant its individual inclusion? Also, 'open' appears to be a somewhat contentious term, akin to 'free.'

Contrastingly, I found that the principles of digital corporate responsibility are better articulated, though, they are not exclusively concerned with sustainability. Here's the link for reference: https://corporatedigitalresponsibility.net/cdr-manifesto-english 

Finally, I have to ask: why aren't the fundamental principles defined in the guideline? It would make sense to include external resources for reference if they are relevant.

**Comment by Emily-Trotter** [comment]
Hello, 
Perhaps it might help to explain how the core principles were/are used within the guideline creation, rather than changing the principles themselves. 

If they are guiding principles then I think they work well as they are: to frame the specifics held within the guidelines. 
The guideline content itself is very rich with detail, and feel quite technical, so it helps to have these wider, more open "guiding principles" at the top level before delving in.

**Comment by AlexDawsonUK** [comment]
@Emily-Trotter I did introduce them at the top in [Section 1.2](https://w3c.github.io/sustyweb/#wsg-layers-of-guidance) (Principles > Guidelines > Success Criteria > Etc), and they are defined (and linked to there) within the glossary - but I take onboard your point that the introduction can always do with some enhancement.

**Comment by timfrick** [comment]
I'll also add here that it was important to align these guidelines with existing sustainability reporting frameworks as digital sustainability isn't often included in those. This is why all guidelines have been mapped to specific GRI standards. Also, these frameworks define sustainability as ESG (environmental, social, and governance/economic), so it is intentional that the guidelines include all three as opposed to just environmental or energy/carbon-related recommendations. For example, we can't have a sustainable future without privacy and accessibility. We made every effort to steer clear of carbon tunnel vision while also acknowledging that energy and emissions are critical to the work we're doing. 

From these comments, I can see that both the glossary and principles, layers of guidance, etc. in the beginning could stand to be more explicit about this. Noted. We'll work on that.

**Comment by gagarine** [comment]
@all Thanks the clarifications.

The comment by @timfrick make total sense to me. This is the information I missed in the intro :).

As noted part is "onboarding" problem, concretely:
- On the point 1.2.1, I was not able to understand where those 6 principles come from and why they was chosen.
- The link https://www.sustainablewebmanifesto.com/ felt a bit weak. I actually knew the website but for me it was not in my radar as having a strong authority. The website is not clear about how they the 6 principles come up.

Side note: Is the link to the sustainablewebmanifesto important or all the information contained in the website could be integrated in the document (we still a link but only to give credit to the source).

**Comment by AlexDawsonUK** [comment]
I can see your point that there is the potential for ambiguity.

As a resolution, because our guidelines are already so well tied into established standards, regulatory frameworks, and evidence backed material throughout; rather than attempting to bind ourselves to a manifesto (which can become opinionated rather than objective or evidence lead), it may make sense to remove that small section and simply integrate the manifesto reference (as you mentioned) into the document (where appropriate) to showcase good practice in action (as it's signature backed it does hold the authority of the high profile individuals and organizations who pledged).

**Comment by timfrick** [comment]
The Sustainable Web Manifesto was authored by a team of over a dozen
leaders in the field of web sustainability, so it probably has the
requisite authority to serve as a quoted source. With that being said, I
agree that the principles on their own without an explanation (and linked
source) are vague at best.

Also, we should be sure to include in the Principles section that we
intentionally took an ESG approach to sustainability (which is also
reflected in the manifesto) so as to align the guidelines with existing
reporting standards. That seems important to mention right up front.

*Tim Frick*
(he/him)
Mightybytes <https://www.mightybytes.com/>
773-561-7529

*Mightybytes is a Certified B Corporation.*
Find out how that helps us run a more purpose-driven company
<https://www.mightybytes.com/b-corporation/>.

**Comment by AlexDawsonUK** [comment]
We have added necessary context to the principles section and an additional ESG definition to the specification.
Changes will be reflected once the second draft is ready to be published.
