### ISSUE TITLE
Clarify the goal of the guideline: Sustainability VS Social responsibility VS Environmental impact VS CO2 emission mitigation

### ISSUE THREAD

**Issue by gagarine** [w3c/sustyweb#6]
The guideline goal is primarily about reducing C02 emission? Or reducing environmental impact ? Or are being more responsible in general?

"Sustainability" is strongly linked in environmental impact and even often limited to C02 emission.
"Sustainability" may be misleading if the guideline ambition is to be about "(Corporate) Digital (Social) Responsability".

The intro is clearly about "environmental impact".

> Web Sustainability Guidelines (WSG) 1.0 covers a wide range of recommendations for making websites and products **more sustainable**. Following these guidelines which utilize environment, social, and governance (ESG) principles throughout the decision-making processes, you can **minimize your environmental impact** through a mixture of user-centered design, performant web development, renewable infrastructure, sustainable business strategy, and (with metrics) various combinations of those mentioned.

In that case the guide would benefit from defining "more sustainable", what go in this scope and what is out of the scope.

Their is an opportunity to have an extra chapter in the intro  "What is Web Sustainability?" (and how it relate to other approach) and extend the abstract accordingly.

Especially has the confusion is quiet common around the discussion regarding the topic. For example, often you hear "Digital Responsibility" when people mean "Environmental impact". Or their on https://sustainablewebdesign.org/ it's unclear what problem they try to tackle:
<img width="835" alt="image" src="https://github.com/w3c/sustyweb/assets/164074/46aebffc-3378-407f-ae72-26851808dece">

**Comment by AlexDawsonUK** [comment]
While the primary focus of our guidelines is sustainability in the environmental impact sense, as you read through the guidelines there are a large number of overarching key references to variables which can in-turn have a some form of impact (as a by-product) such as ethical behavior, good governance, inclusiveness (accessibility), privacy by design, social responsibility and CDR. In addition, we have aligned our guidelines with existing standards such as GRI, and identified points beyond reduction of CO2 (such as water waste and raw material conservation like paper) where appropriate to avoid limiting or narrowing the definition. These are repeated where necessary to reinforce the point and cited with sources wherever possible to validate the claims.

I take onboard your point that further clarification could be useful to note how it differs from other approaches, but we have deliberately chosen to keep the definition broad. This is because web sustainability is an evolving field, and has not been so explicitly defined, which is a good thing due to our ongoing efforts to give broad guidance on the multitude of variables which can have an impact.

**Comment by timfrick** [comment]
My comment about our ESG approach to sustainability, which is increasingly common, is appropriate here as well. https://github.com/w3c/sustyweb/issues/5#issuecomment-1714049626

**Comment by gagarine** [comment]
@timfrick yeah I realize now it's a similar subject.

@AlexDawsonUK I think what you just explained could be added with 2-3 sentence in the doc. To give context.

**Comment by AlexDawsonUK** [comment]
We have added necessary context to the principles section and an additional ESG definition to the specification.
Changes will be reflected once the second draft is ready to be published.
