### ISSUE TITLE
Comment on 2.14 Write With Purpose, in an Accessible, Easy To Understand Format

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#68]
Hi, I had fun reading the WSG today. I am very happy reading it again and learning more each time.  I kind of had one thought, that this article brings to mind: https://www.theverge.com/c/23998379/google-search-seo-algorithm-webpage-optimization .

One of the criteria is:

> Prioritize SEO at early design stages and throughout a product or service’s lifecycle to improve content findability.

That Verge article to me shows how SEO techniques can have a impact on the websites that may be in favor of search engines over actual users? Is SEO really strictly a way to write with purpose and accessible? 

You want the content to be findable, but there seems to me to be a balancing act between original clear content and then SEO techniques which can actually obscure that. Using Semantic HTML and other techniques will help SEO and readability but SEO on its own as a priority seems less clear ?

Thank you for any consideration of this comment

**Comment by AlexDawsonUK** [comment]
I think your comment actually sums up why the SEO criteria was included. Using Semantic HTML and other non-UX invasive / non-offensive techniques (such as microdata) helps content become easier to locate on the Web. In SEO circles this is referred to as "organic" SEO (because it's not trying to game the search engines - it's just using good practices).

That being said people do abuse SEO and it could have a sustainability cost in terms of preventing people finding what they want, impersonation (from bad actors), additional rendering time (so emissions triggered by spiders indexing sites and by visitors loading stuff they won't benefit from). Potentially another SC under [2.11](https://w3c.github.io/sustyweb/#avoid-manipulative-patterns) (Avoid Manipulative Patterns) might be useful? Example...

**SC: Search Engine Optimization**

Optimization for search engines, social networks, and third party services should be organically lead with good coding practices and user-experience being the focus, not manipulating the services to gain greater priority through obfuscating content, pages, websites or applications with redundancy or non-useful and optimized (to the visitor) material.

**Comment by airbr** [comment]
Thanks @AlexDawsonUK , agreed. This one resonates with my experience of the web- there are definitely websites that use non organic techniques and sometimes you can really tell.

**Comment by mgifford** [comment]
Having one voice, and a consistent format, will be such a huge advantage over WCAG.   
  
I'm not sure how that will align with the general W3C approach.

**Comment by AlexDawsonUK** [comment]
This SC has now been included within the living draft, it will be published within the next version of the specification.
