### ISSUE TITLE
New SC for 3.7: Third-party Preferences

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#71]
**Problem:** Third-party code causes a LOT of sustainability issues, so visitors need to be able to manage this to some extent.

**Solution:** Third-party products, services, libraries, and frameworks are often a source of sustainability issues which cannot be controlled or managed by the first-party provider of a service. While many do provide benefits to a website, the need to justify their inclusion should be made not only by those creating the product or service but also be able to be controlled by the consumer. As showcased with cookies, websites or applications should provide a similar mechanism of disabling or refusing non first-party features (with explanations of their purpose) - unless such features can be proven as critical for functionality.

@Nahuai

**Comment by Nahuai** [comment]
Thanks for creating this Alex!
I think you expressed really well what I meat with my commentary in the meeting, you can go ahead with the issue.
If you need some help from my side, please let me know.

**Comment by AlexDawsonUK** [comment]
This SC has been included within the living draft, it will be released in the next published version of the specification.

**Comment by mgifford** [comment]
A lot of 3rd party code can likely be turned off.   
  
Marketing teams want Google Analytics, because that is what they know, but there are other approaches that are better for sustainability and privacy.   
  
A good open source option we might be able to recommend is [https://plausible.io](https://plausible.io/)   
  
I think that tools like WCAG-EM should be able to refer to open source tools that meet the requirements.   
  
We can recommend doing some sort of "spring cleaning" of 3rd party tools.  If a JS tool isn't being used, it should be removed.

**Comment by chrisn** [comment]
It's not the place for a (potential) W3C standard to make specific recommendations for or against particular products. The focus here should be on how to measure sustainability impacts, so people can make informed decisions about which tools to use.

**Comment by AlexDawsonUK** [comment]
Yes, this is something that needs to be underlined.

Also just following up that appropriate management of third-party tooling is covered by [3.17](https://w3c.github.io/sustyweb/#manage-dependencies-appropriately) and the recommendation to use open source is covered by [5.28](https://w3c.github.io/sustyweb/#use-open-source-tools), this should have broad enough coverage without naming specific offenders.
