### ISSUE TITLE
Proposed guideline: Choose tooling and / or programming language appropriate to the task.

### ISSUE THREAD

**Issue by BezPowell** [w3c/sustyweb#74]
Apologies for the issue spam today! This proposed guideline is tangentially related to `5.27 Define Performance and Environmental Budgets` and the proposal I made earlier today `Process data close to the source`, but feels to me like it is something that should be mentioned explicitly.

An idea for wording is below, but I'm not sure how to word success criteria. What I think the guideline should cover is that there are many different ways to achieve the same task in programming, and each can have a very different cost in-terms of execution time and energy usage. When implementing any piece of functionality, large reductions in potential emissions can be achieved by choosing the appropriate language for the task.

This doesn't just apply on the backend, but to the frontend as well. Solutions such as CSS in JS, hydrating JSON on the client, or writing client side code in Python and running an additional interpreter (something I've seen on a number of occasions over the last 12 months) will add additional overhead compared to using the language best suited to the task; the one that the browser is optimised to process.

### Choose tooling and / or programming language appropriate to the task.
Many tools and programming languages are optimised for performing particular tasks, and utilising those most appropriate to the problem domain can reduce computational cycles and energy usage. An algorithm implemented in a compiled language such as C or Rust, for example, can have greatly reduced execution time and energy usage compared to the same algorithm written in an interpreted language like Python or JavaScript.

##### Environmental:
Using a language with lower energy requirements means more requests can be processed for the same energy 'cost'.

##### Performance:
Languages with low energy requirements tend to also exhibit low execution time, leading to improved performance.

##### Economic:
Choosing tooling appropriate to the problem domain should save on server resources, allowing the use of cheaper hardware or running more processes on the same system.

#### Accessibility:
Reducing an app's dependency on client-side JavaScript will boost resilience to poor network conditions and maintain usability in environments where it is unavailable (behind corporate firewalls, for example).

### References
- https://www.researchgate.net/publication/320436353_Energy_efficiency_across_programming_languages_how_do_energy_time_and_memory_relate

**Comment by AlexDawsonUK** [comment]
You're not spamming at all! This was something brought up in the meeting by **Loren Velasquez**, though I was struggling to create a dedicated guideline for it as there was a lot of overlap with existing Guidelines and Success Criteria. I agree that the issue runs across both front-end and back-end with the use of tooling (though tooling can reduce developer screen time which can be a sustainability benefit), and choosing the best language for the job is important - though potentially not enough research has been done to conclusively determine the best language (there are only a couple of papers on the subject and they are quite subjective). I'm going to investigate this further to see how the guidelines can be tightened to potentially add additional Success Criteria around **Language Use** and **Compilers** (bundlers, interpreters, etc) to optimize things further.

If there's anything which might add weight to the argument keep adding it to the below conversation!

**Comment by BezPowell** [comment]
Adding in a few more benchmarks for comparison. All of these only measure performance, so might not necessarily correlate to energy usage etc. They're also all benchmarks, so again might not translate to real world performance, but at least do have objective numbers for the tests run.

- https://www.techempower.com/benchmarks/#hw=ph&test=composite&section=data-r22
- https://attractivechaos.github.io/plb/
- https://web-frameworks-benchmark.netlify.app/result
- https://niklas-heer.github.io/speed-comparison/

It's interesting how widely the results vary between different benchmarks. JavaScript is almost always slower than C, for example, but the magnitude of the difference varies depending upon the test. A very good example that benchmarks tend to be highly optimised and a good indication of the optimal performance of a language; it's very possible to write something in Rust that is many times slower than the equivalent written in Python, even if the theoretical threshold of performance is faster.

**Comment by fullo** [comment]
> Economic:
> Choosing tooling appropriate to the problem domain should save on server resources, allowing the use of cheaper hardware or running more processes on the same system.

It depends on the numbers; sometimes, it is better to have a slower language but very supported and with a good code base to spend less resources in developing code than writing everything in assembly for the sake of the performance. From an economic point of view, we should see the cost of the whole development process (people, tooling, deployment, execution, maintenance) rather than only the execution part.

> c. They're also all benchmarks, so again might not translate to real world performance, but at least do have objective numbers for the tests run.

I do not believe in benchmark and speed comparison about program languages, and I think we should not bring these topics on the tab, but we should remind to the developer that they should run some Quality Assurance/Performance tests time by time.

**Comment by AlexDawsonUK** [comment]
> It depends on the numbers; sometimes, it is better to have a slower language but very supported and with a good code base to spend less resources in developing code than writing everything in assembly for the sake of the performance. From an economic point of view, we should see the cost of the whole development process (people, tooling, deployment, execution, maintenance) rather than only the execution part.

I was (a few days ago) going to say something along the same lines, however it came to mind that one of the problems with sustainability is that execution of code is almost always the most important value. People, tooling, deployment and maintenance do take resources and time however with the exception of maintenance (which occurs semi-occasionally), the other instances only occur on the first instance of creation and thus the carbon impact can be recovered if more intensity leads to an overall less intensive overall experience.

**Example 1:** An offline application is produced using Electron, it's quick and easy to produce so doesn't utilize much in the way of resources, it's easy-to-learn so it's carbon path is short, and the final product can be easily maintained as it's just HTML, CSS & JS. But here is the problem, Electron is a Mammoth that uses (generally speaking) a LOT of CPU, GPU, RAM and HDD. Sure it can be highly optimized (which again is a carbon intensive process), but statistically speaking it isn't. So you say have 1 million users, all burning through system resources (and battery) having to recharge regularly because it is heavily resource intensive. In addition, old devices can't handle it leading to e-waste.

**Example 2:** You have the same application written natively using C, it's lightweight, uses barely any resources - however because it takes experience and effort to create (and manage) has a long-tail carbon footprint. This is carbon heavy to create as it requires people and their years of training. There is a massive up-side though, once it's built and deployed, that million user-base can use it on old devices (so less e-waste), and it won't thrash their equipment leading to higher emissions from constant device recharging (or electrical usage).

This is the case that I make. Optimizing a code-base for the sake of performance, especially if there is a reasonable user-base involved justifies the time and effort into using a faster or more efficient language. Emissions need to be considered for every single visit, not just on the execution (as those who content is rendered for often trigger an emissions cost). It's something I've been doing extensive research into, and if the evidence suggests some languages are environmentally poor, they should either be optimized or reconsidered.

**Comment by BezPowell** [comment]
> I do not believe in benchmark and speed comparison about program languages, and I think we should not bring these topics on the tab, but we should remind to the developer that they should run some Quality Assurance/Performance tests time by time.

Can I ask why you don't believe in speed comparisons between programming languages? Benchmarks obviously don't always translate to the real world, but they do tell us that in those specific conditions something ran faster than something else. When you then look at an aggregate of different benchmarks and find that (for example) C has a faster execution time than JavaScript in a majority of cases, I feel it's not unreasonable to infer that in many situations it might be faster. I'm very open to being persuade otherwise, however.

@AlexDawsonUK I'm in total agreement. The nature of software in general, and especially the web, means that there is almost always going to be far more users than there are developers. Even subtle improvements to user experience (including performance) are therefore going to have a much greater impact than the other way around; wasting a few hours of a single developers time is annoying, but wasting even a fraction of that for several thousand users is going to have a much bigger impact.

A recent personal anecdote to that effect is that I last year I entirely rewrote our main data transformation process at work. The old one was written in Groovy (not a language I had heard of before) and had been added to over many years by different developers; it took on average over 17 hours to process 3.5 million records, frequently failed without warning, and spent a long time doing totally unnecessary conversions.

Over the course of 3 months I spent a good portion of my working time slowly digging through the database schema and the tangled mess of the old code base to understand exactly what it was doing. I then rewrote the whole thing in pure SQL, with a simple cli written in rust that handled logging and parallel execution of scripts. I dread to think how many hours and false starts it took me, but the end result is that the new process is far more reliable, reports any failures or data validation errors to us, and now executes in under 15 minutes.

The new process has been in place for around 6 months now and so far we've had no failures. As the old one was executing once a week, it's already save far more hours of processing time than the man hours I put into rebuilding it; not a direct comparison, I know, but an indication of how much wasted time can be caused by inefficient code.

**Comment by BezPowell** [comment]
@AlexDawsonUK That's a very good point and something that I suspect might be a bit of a balancing act. In an ideal world (at least, as far as performance is concerned) all software would be written in assembly by developers who never make mistakes. Of course, we don't live in an ideal world (I've mucked around a bit with assembly and, personally, it scares me silly) so have to find some form of compromise; as you say, not everyone is comfortable using strictly-typed compiled languages and they certainly aren't suitable for all tasks.

What we perhaps need is a gentle nudge in the right direction, as it were? A mention in more general performance guidelines that the choice of language can make a difference, and that, all other factors being equal, not building your app in Electron would probably be better for your users and environment.

**Comment by AlexDawsonUK** [comment]
I've created a SC in 3.22 within the [living draft](https://w3c.github.io/sustyweb/drafts/) around this subject.
These will in due course be published within the main specification at the next draft version mark.

**Comment by fullo** [comment]
@AlexDawsonUK my statement
> It depends on the numbers;

It is the very same example you provided, if I have 1mln users I will not use electron, maybe neither assembly or C but something in between. Something to efficiently deliver and maintain code and not have the CPU clogged. But, if my application will be used only by a bunch of people, electron IMHO is the right choice. 

@BezPowell because in my experience on web development, the programming language rarely is the bottleneck, I/O, caching, assets, and client-side experience are. We are talking about 98% of the web applications online, indeed you have a 2% which need to crunch tons of data and to run at light speed, but those are edge cases scenarios and have to be treated as such. Moving discussions far away from business needs and too close to benchmark enthusiasts isn't the best course of action. Performance without maintainability is never a good business choice (as in the 3rd sustainability pillar).

Btw in the years I moved from a pure performance approach, I was an advocate for WPO practices (Web Performance Optimization) in early 201x and wrote a couple of ASM+C extensions for PHP, to a more tech-to-business savvy approach. Maybe I'm only getting older and grumpy :D

(sorry for the late reply; I missed the notification)
