### ISSUE TITLE
STAR 1.0 Draft suggestion - Consider elaborating WD21-1: Encourage the Use of More Sustainable Creation Toolchains; Also Examples minor typo

### ISSUE THREAD

**Issue by airbr** [w3c/sustyweb#86]
Hello,

I found WD21-1 exciting to see included as a technique but it seems to be written very much in the passive voice.

I thought

> This should take into account the creator's ability as well as the tooling dimension

could be simplified if not actually shorter by explaining:

> "Build steps and tooling add additional complexity to a project and this should be weighed against other factors to enable sustainable creation toolchains"

My honest thought is that this  paragraph below does not explain much that a significantly informed reader would not already know. I think it could be trimmed possibly for general usage.

> For machine testability, internal access may be required if no traces of the creation tool have been left in the production code. If the production code does however contain fingerprints of the tool that created it, recommendations can be made to prioritize static over dynamic and flat-static over generated-static as reducing the processing effort on servers and client machines is meaningful.

Finally there is a small typo in the examples section of Jekyll as Jeckyll

**Comment by AlexDawsonUK** [comment]
> This should take into account the creator's ability as well as the tooling dimension
> could be simplified if not actually shorter by explaining:
> "Build steps and tooling add additional complexity to a project and this should be weighed against other factors to enable sustainable creation toolchains"

I like that, but I've also added a small bracket nod to individuals who may be limited by their ability (for example NoCode or WYSIWYG editor users, kids learning tech at school, people new to the web, etc) so it feels sensible to include:

"Build steps and tooling add additional complexity to a project and this should be weighed against other factors **(such as individual / team ability)** to enable sustainable creation toolchains."

> My honest thought is that this paragraph below does not explain much that a significantly informed reader would not already know. I think it could be trimmed possibly for general usage.

Remember, with potential W3C specifications, we have to aim for every kind of audience and not assume knowledge about a subject. It might be second nature thinking for us, but there could be a student or first timer using this work (or some variant of it) in order to make meaningful change, so I wouldn't want to eliminate basic general understandings.

> Finally there is a small typo in the examples section of Jekyll as Jeckyll

Good spot! Fixed. All the updates are now visible within the draft of [STAR](https://w3c.github.io/sustyweb/drafts/star.html).
