### ISSUE TITLE
Sustainability Scheme

### ISSUE THREAD

**Issue by AlexDawsonUK** [w3c/sustyweb#93]
**Issue:** Browsers have the potential to verify the security of a website using certification processes such as SSL and this is verified within the address bar with a high user-experience recognition. Within the scope of sustainability, the ability for a central authority to offer a similar scheme by using machine-testability (against perhaps the WSGs) to showcase the level of sustainability of a website and then providing certification for that website or application, a similar mechanism could be achieved for allowing website owners to have recognition of their efforts within browsers (if implemented by user-agents in an accessible manner). This could also be accompanied by a HTTP header if certification exists?

**Slack Discussion:** https://w3ccommunity.slack.com/archives/C02JETQAQG4/p1714577798464149

**Note:** [EU CIRPASS Scheme](https://cirpassproject.eu/) could be used as it uses W3C standards to provide product passports which could be extended for digital products and services as a container format (RDFa or XML) for certificates being issued.

**Comment by boehs** [comment]
This is my mockup of what this could look like on the agent:

![image](https://github.com/w3c/sustyweb/assets/51836263/83d37135-0950-473f-bfee-6d61e6f6cbe8)

The initial proposal was simply header based, with the logic that an authority introduces a lot of complexity and that lying to consumers would be bad press, and would hence not be done. The counter argument is that users may not trust these claims if they aren't verifiable, and that it could be illegal to make such claims in some jurisdictions.

The logic for this proposal is that awareness efforts could be beneficial:

> This would help businesses proudly show their commitment to the climate, and would help users be more aware of the way the web impacts the climate.

If an authority based system is established, this introduces complexity, and one unanswered question is if smaller businesses would be willing to put the effort into acquiring this certification. If the *host* is powered by green energy and hence only the host requires verification by the authority, this could be a good middle ground as websites would be automatically opted in. The problem is that there is more nuance than that. You cannot simply verify IP blocks, because If the website makes use of a reverse proxy like Cloudflare, both the proxy and the origin need to be audited. 

A pro of authority based systems is that this could be used for more significant advantages in the future. For instance, search engines could give a SEO advantage to green websites, and could be confident it wouldn't be abusable

**Comment by AlexDawsonUK** [comment]
**Note:** This [HTTP response header proposal](https://www.ietf.org/archive/id/draft-martin-http-carbon-emissions-scope-2-00.html) (draft) from the IETF could play a part, though its scope is too limited for legal compliance as it only has coverage for co2 and doesn't account for other forms of emissions.

**Comment by mrchrisadams** [comment]
hi @AlexDawsonUK - this is pretty much what we were going for with Carbon.txt.

We have it off the Green Web Foundation domain, because in the long run we'd like to develop it into a convention that would be standardised, so the things we look for in our own verification process can be administered by other providers, just like who we have multiple SSL cert issuers.

https://carbontxt.org

There's some more about this that we're planning to publish over the summer, but it's quite a difficult problem to solve even if you have browsers acting as "user-agents of change" 🥁

**Comment by AlexDawsonUK** [comment]
@mrchrisadams I've been aware of the carbon.txt project for a good while and its awesome to see it getting increased development (we mention it in the WSGs and STAR).

We have a certain level of machine-testability within the WSGs so whether that could be utilized in some future certification process to provide a wider scope than what just the carbon format offers, who knows!

**Comment by fullo** [comment]
> The initial proposal was simply header-based, with the logic that an authority introduces a lot of complexity and that lying to consumers would be bad press, and would hence not be done. The counterargument is that users may not trust these claims if they aren't verifiable and that it could be illegal to make such claims in some jurisdictions.

In the EU it will be illegal to make green claims without having scientific data to demonstrate declarations. 

See the Green Claim Directive:
- https://environment.ec.europa.eu/topics/circular-economy/green-claims_en
- https://www.europarl.europa.eu/RegData/etudes/ATAG/2024/759609/EPRS_ATA(2024)759609_EN.pdf

The complexity of sharing dynamic information about emissions is relatively high, and self-made claims IMHO are not a practical solution (at least in the EU).

IMHO carbon.txt is a good starting point for testing how people will use it.

as a side note, on the hardware side of the story, OpenTelemetry is getting more and more interesting, there's a discussion to extend it to [calculate the emission of infrastructure in real-time](https://github.com/open-telemetry/community/issues/2020) and also the [Impact Framework](https://github.com/Green-Software-Foundation/if) of GSF is evolving relatively fast and could be evaluated in a scenario that uses its manifest to generate a carbon.txt file from scratch. Here is another document regarding the [Real Time Energy and Carbon Standard for Cloud Providers](https://github.com/Green-Software-Foundation/real-time-cloud/) by GSF.

**Comment by AlexDawsonUK** [comment]
This previously open issue is now [under the review of the Interest Group](https://github.com/w3c/sustainableweb-wsg/issues/11), discussion and resolution will continue there.
