### ISSUE TITLE
Provide guidance on tradeoffs

### ISSUE THREAD

**Issue by jyasskin** [w3c/sustyweb#98]
https://w3c.github.io/sustyweb/#consider-sustainability-in-early-ideation recommends using paper over electronic media, but of course creating and transporting a piece of paper does cost energy, water, trees, etc., which need to be weighed against the electrons it could replace. Without information on the rough costs of each option, it's hard to be confident that we're balancing optimally.

There are similar tradeoffs in https://w3c.github.io/sustyweb/#assess-and-research-visitor-needs and https://w3c.github.io/sustyweb/#adapt-to-user-preferences (tailored experiences mean more resources used to produce and store those experiences), https://w3c.github.io/sustyweb/#rigorously-assess-third-party-services (a 3p service can be built once for many clients), https://w3c.github.io/sustyweb/#minify-your-html-css-and-javascript (minified code makes View Source less useful, but View Source is important for the long-term sustainability of training new developers), and elsewhere.

**Comment by AlexDawsonUK** [comment]
I'm linking this to issue #101 as they have similar concerns with the variables at-work in an environment that may impact the cost (beneficially or negatively) and how we choose to measure it.

We need to provide more coverage in this area (especially the negatives with benefits) so I've added it to the todo list.

**Comment by AlexDawsonUK** [comment]
I've been playing around with the idea of providing a tradeoff's section with each guideline (as we have a benefits section) but because many sustainability issues have similar or the same compounding issues surrounding them (but with just a few differences), it seems redundant to repeat this information throughout the specification.

Therefore I will resolve to add an section on the subject to the introduction covering the issues that affect this subject matter and will tie it into our measurability data once available to determine what impact such variables may have upon the choices made. As such this issue will await the outstanding measurability issue to be resolved before proceeding.
